#!/bin/bash

s="AAGTGCTTAAGTGCTATGAAGTGCTAAGTGCTTTAAGTGCTAGAAGTGCTAAGTGCTCACCACAAAAGTGCTAATGTCGAGAAAAAAGTGCTAAGTGCTGAGGAGAAAGTGCTAAGTGCTTTGATGTAAGTGCTTTACCTAAAGAAGTGCTGTGCAAGTGCTGAAGTGCTCTCTGAAGTGCTTTAAACCATAAGTGCTAAGAAGTGCTCTCAAGTGCTCCAAGTGCTTATAAGTGCTAAGTGCTGAAGTGCTTGCACCTGCAAGTGCTAAGTGCTAAGTGCTTTGAAGTGCTGAAAAGTGCTTCCCAAGTGCTCTTTGAGTAAAGTGCTAATAAAGTGCTAAGTGCTGAAGTGCTAAGTGCTTCGGGAAGTGCTCAAGTGCTTGAAAGTGCTTGCAAGTGCTTAATGAAGAAGTGCTCAAAGTGCTACCAAGTGCTATTAAAGTGCTCCCAAGTGCTCTGAAGTGCTGGTGAAGTGCTCTTAAAGTGCTCTCAAGTGCTAAGTGCTGCTAGGCCTAAGTGCTTTCAAGTGCTTAAGTGCTGTTAAGTGCTAAGTGCTTCTTCAGGCAAGTGCTAAGTGCTGATCGAAGTGCTCTCGTAAGTGCTAATAAGTGCTCTAAAGTGCTGCCCCAGCCGCAAGTGCTCCAAAGTGCTAAGTGCTAACAAGTGCTTTATGAGAAAGTGCTCAAGTGCTTTGAAGTGCTCCAAAGTGCTAAGTGCTAAGTGCTTTTCTATTGAAGTGCTGGGAGAGTTACAAGTGCTAAGTGCTAAGTGCTTGAAGTGCTTAAGTGCTAAGTGCTATGAAGTGCTCAAAGTGCTCGTTAAGTGCTATTAAGTGCTTAAGTGCTAGGAAGTGCTTTCCACAAGTGCTAAGTGCTCTTAAGTGCTGCTAAGTGCTCATAAGTGCTAAGTGCTTGTCAAGTGCTGCCAAGTGCTAAAGTGCTAAGTGCTACAGCAGCAAGTGCTAAGTGCTATAAGTGCT"
t="AAGTGCTAA"
result=""

for (( i=0; i<=${#s}-${#t}; i++ )); do
    if [[ ${s:$i:${#t}} == $t ]]; then # Cut a portion of the string s, starting from position i and with a length equal to the length of t
        result="$result$((i+1)) "  # Append the position to the result string
    fi
done

echo $result  # Output the result string

# Problem in link: https://rosalind.info/problems/subs/